import{a as S,S as q,i}from"./assets/vendor-frHSA4Lh.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(t){if(t.ep)return;t.ep=!0;const a=r(t);fetch(t.href,a)}})();const v="https://pixabay.com/api/",$="50732849-21223ac287faa79ee0d00336e",m=15;async function p(e,s=1){const r=new URLSearchParams({key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:m}),o=`${v}?${r}`;try{return(await S.get(o)).data}catch(t){throw t}}let d;function y(e){const s=document.querySelector(".gallery"),r=e.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}" title="${o.tags}">
        <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      </a>
      <div class="info">
        <ul class="info-list">
          <li><span>Likes</span><br>${o.likes}</li>
          <li><span>Views</span><br>${o.views}</li>
          <li><span>Comments</span><br>${o.comments}</li>
          <li><span>Downloads</span><br>${o.downloads}</li>
        </ul>
      </div>
    </li>
  `).join("");s.insertAdjacentHTML("beforeend",r),d?d.refresh():d=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function P(){const e=document.querySelector(".gallery");e.innerHTML=""}const f=document.querySelector("#search-form"),h=document.querySelector("#loader"),R=document.querySelector(".gallery"),L=document.querySelector(".btn-load-more");let c=1,g="",w=0;f.addEventListener("submit",async e=>{e.preventDefault();const s=e.target.searchQuery.value.trim();if(s===""){i.warning({message:"The field must not be empty",position:"topRight"});return}g=s,c=1,P(),l(!1),b(f),n(!0),await new Promise(r=>setTimeout(r,1e3));try{const r=await p(g,c);if(w=r.totalHits,n(!1),r.hits.length===0){i.info({message:"Sorry, there are no images matching your search query.",position:"topRight",color:"red"});return}y(r.hits),l(r.hits.length>=m)}catch(r){n(!1),i.error({message:`Error: ${r.message}`,position:"topRight"})}f.reset()});L.addEventListener("click",async()=>{c+=1,b(R),n(!0),l(!1),await new Promise(e=>setTimeout(e,1e3));try{const e=await p(g,c);n(!1),y(e.hits),A(),document.querySelectorAll(".gallery-item").length>=w?(l(!1),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"red"})):l(!0)}catch(e){n(!1),i.error({message:`Error: ${e.message}`,position:"topRight"})}});function n(e){h.classList.toggle("hidden",!e)}function l(e){L.classList.toggle("hidden",!e)}function b(e){e&&e.insertAdjacentElement("afterend",h)}function A(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
